[20:01] <543d7fd1db8155e6700cb700> I'm also running into an issue downloading datasets with `datasets.fetch_mldata()` (cc @RohanVB)
[20:02] <543d7fd1db8155e6700cb700> urlopen() fails with a "Connection reset by peer", though downloading the same URL with curl works (but curl --verbose shows a warning)
[20:02] <543d7fd1db8155e6700cb700> Did mldata.org change their server, and it now does something weird with HTTP that Python's urllib2 can't handle?
--------------------------------------------------------------------------------------------------
[20:04] <543d7fd1db8155e6700cb700> ``` $ curl -LI -X GET http://mldata.org/repository/data/download/matlab/mnist-original HTTP/1.0 301 MOVED PERMANENTLY Date: Mon, 21 Nov 2016 20:03:05 GMT Content-Type: text/html; charset=utf-8 Location: http://mldata.org/repository/data/download/matlab/mnist-original/ Server: fapws3/0.9  HTTP/1.0 200 OK Content-Length: 55440440 Content-Disposition: attachment; filename=mnist-original.mat Vary: Cookie Server: fapws3/0.9 Date: Mon, 21 Nov 2016 20:03:05 GMT Content-Type: application/x-matlab  $ python -c 'import sklearn.datasets; sklearn.datasets.fetch_mldata("MNIST original")' Traceback (most recent call last):   File "<string>", line 1, in <module>   File "/home/vagrant/.virtualenvs/digits-sklearn-opencv/local/lib/python2.7/site-packages/sklearn/datasets/mldata.py", line 143, in fetch_mldata     mldata_url = urlopen(urlname)   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen     return opener.open(url, data, timeout)   File "/usr/lib/python2.7/urllib2.py", line 435, in open     response = meth(req, response)   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response     'http', request, response, code, msg, hdrs)   File "/usr/lib/python2.7/urllib2.py", line 467, in error     result = self._call_chain(*args)   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain     result = func(*args)   File "/usr/lib/python2.7/urllib2.py", line 651, in http_error_302     fp.read()   File "/usr/lib/python2.7/socket.py", line 355, in read     data = self._sock.recv(rbufsize)   File "/usr/lib/python2.7/httplib.py", line 612, in read     s = self.fp.read(amt)   File "/usr/lib/python2.7/socket.py", line 384, in read     data = self._sock.recv(left) socket.error: [Errno 104] Connection reset by peer ```
--------------------------------------------------------------------------------------------------
[20:14] <543d7fd1db8155e6700cb700> Wow now I'm seeing "Connection reset by peer" from curl as well. I'll just try and self-host that somewhere, if I can ever grab it
--------------------------------------------------------------------------------------------------
[20:22] <543d7fd1db8155e6700cb700> There is no way to load a MATLAB mldata file from a different URL though, is there?
--------------------------------------------------------------------------------------------------
[21:25] <574454a0c43b8c601974a563> Today I found https://github.com/scikit-learn-contrib/scikit-learn-contrib , is it possible to add https://github.com/nok/sklearn-porter ? But it isn't an estimator like one of the listed examples. Who can help me?
--------------------------------------------------------------------------------------------------
