[23:46] <589208e2d73408ce4f4770c4> Hi,all I am using scikit 0.19.1 I generated a training model using random forest and saved the model. These were done on ubuntu 16.01 x86_64. I copied the model to a windows 10 64 bit machine and wanted to reuse the saved model. But unfortunately i get the following Traceback (most recent call last): File "C:\Users\PC\Documents\Vincent\nicholas\feverwizard.py.py", line 19, in rfmodel=joblib.load(modelfile) File "C:\Python27\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 578, in load obj = _unpickle(fobj, filename, mmap_mode) File "C:\Python27\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 508, in _unpickle obj = unpickler.load() File "C:\Python27\lib\pickle.py", line 864, in load dispatchkey File "C:\Python27\lib\pickle.py", line 1139, in load_reduce value = func(*args) File "sklearn\tree_tree.pyx", line 601, in sklearn.tree._tree.Tree.cinit ValueError: Buffer dtype mismatch, expected 'SIZE_t' but got 'long long'  What could be happening? Is it because of a switch from ubuntu to windows? However i am able to reuse the model in my ubuntu.
