[05:50] <5ee61de0d73408ce4fe6d981> I get an error trying to use a callable for metric with KNN. What is the correct way to use it?  ``` clf = KNeighborsClassifier(metric=dm.get_metric("minkowski")) clf.fit(X,y)  ValueError: Metric '<sklearn.metrics._dist_metrics.EuclideanDistance object at 0x000001ECEC658DD0>' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function. ```
[17:30] <matrix-hansuke:matrix.org> https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
[18:32] <567f5d7716b6c7089cc043a8> @amy12xx it's always easier for people to give you a meaningful answer if you paste a minimally reproducible code, which can in its entirety be copy/pasted to produce your issue.
[20:04] <5ee61de0d73408ce4fe6d981> good point :-)
[20:08] <5ee61de0d73408ce4fe6d981> ``` from sklearn.neighbors import KNeighborsClassifier from sklearn.metrics import DistanceMetric as dm from sklearn.datasets import load_iris iris = load_iris() X = iris.data y = iris.target clf = KNeighborsClassifier(metric="euclidean") clf.fit(X,y) clf = KNeighborsClassifier(metric=dm.get_metric("euclidean")) clf.fit(X,y)  Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "C:\Users\Amanda\Miniconda3\envs\mlenv\lib\site-packages\sklearn\neighbors\_classification.py", line 198, in fit     return self._fit(X, y)   File "C:\Users\Amanda\Miniconda3\envs\mlenv\lib\site-packages\sklearn\neighbors\_base.py", line 437, in _fit     self._check_algorithm_metric()   File "C:\Users\Amanda\Miniconda3\envs\mlenv\lib\site-packages\sklearn\neighbors\_base.py", line 374, in _check_algorithm_metric     raise ValueError( ValueError: Metric '<sklearn.metrics._dist_metrics.EuclideanDistance object at 0x0000018099BB9780>' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.  ``` 
